---
title: "Application Study"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preparation

Clean the environment
```{r clean environment}
rm(list = ls())
```

```{r libraries and self-defined funcs}
library(glmnet)
library(reticulate)
library(SAM)
source("../func/misc.R", chdir = T)
source("../func/FBselect.R", chdir = T)
source("../func/stop_cond.R", chdir = T)
source("../func/locs_gen.R", chdir = T)
source("../func/y_gen.R", chdir = T)
source("../func/Vecc_path.R", chdir = T)
source("../func/penalty.R", chdir = T)
source("../func/fisher_scoring.R", chdir = T)
source("../func/PGPR_Yi2011.R", chdir = T)
source("../func/FWDselect.R", chdir = T)
source_python("../func/KISS_GP.py")
source_python("../func/reg_tree.py")
```

```{r sim parms}
nVec <- c(500) # c(500, 5000, 25000)
dVec <- c(10) # c(100, 1000)
rhoVec <- c(0) # c(0, 0.9)
# use seed = 1, 2, 3, ...
seed <- as.numeric(commandArgs(trailingOnly = T)[1])
sigmaSq <- 1
tauSq <- 0.05^2
rSq0 <- c(10, 5, 2, 1, 0.5)^2
d0 <- 5
covFn <- "matern25_scaledim_sqrelevance"
nTst <- 5000
```

```{r some opt parms, eval = T}
var0 <- 0.25
tau0 <- 1e-4
sr0 <- 1e-2
minPosi <- 1e-8
m <- 100
k <- 3
miniQCCD <- 128
miniGrad <- 128
nAvg <- 2
lambVecBrdg <- 4^(rev(-6 : 3))
convQCCD <- 1e-4
convCCD <- 1e-4
cAmij <- 1e-4
maxIterQCCD <- 200
maxIterElse <- 100
maxIterCCD <- 40

covFn <- "matern25_scaledim_sqrelevance"
mini <- T
taper <- T
silent <- F
pen_fun <- pen_avg_brdg
dpen_fun <- dpen_avg_brdg
ddpen_fun <- ddpen_avg_brdg
stop_con_path <- function(scrVec, idxSet, thetaSet){
  min(stop_con_NEW_path(scrVec, idxSet, thetaSet), 
      stop_con_OOS1_path(scrVec, idxSet, thetaSet))
}
ngenPGPR <- 10
theta_gen <- function(){
  c(var0, (runif(d) * 0.2)^2, tau0) 
}
cluster <- makeCluster(min(detectCores() - 1, 16), 
                       outfile = paste0("tmp_seed", seed, ".out"))
```

```{r storage vars, eval = T}
result <- data.frame(matrix(NA, 0, 7))
colnames(result) <- c("n", "d", "rho", "mtd", "scr", "time", "fpos")
idx <- 1
```

```{r main loop}
if(is.null(seed))
  stop("Seed should not be NULL\n")
for(nTrn in nVec)
  for(d in dVec)
    for(rho in rhoVec){
      if(!silent){
        cat("======================================================\n")
        cat("n =", nTrn, "d =", d, "rho =", rho, "\n")
      }
      set.seed(seed)
      if(rho != 0){
        locs <- locs_gen_dp(n = nTrn + nTst, d = d, rho = rho)
      }else{
        locs <- locs_gen_idp(n = nTrn + nTst, d = d)
      }
      theta <- c(sigmaSq, rSq0, rep(0, d - d0), tauSq) 
      y <- MVN_gen(locs = locs, parms = theta, covFn = covFn)
      pIn <- nTrn / (nTrn + nTst)
      spltObj <- splt_locs_y(locs, y, pIn)
      locsTrn <- spltObj$locs1
      locsTst <- spltObj$locs2
      yTrn <- spltObj$y1
      yTst <- spltObj$y2
      # standardize y
      meanYTrn <- mean(yTrn)
      sdYTrn <- sd(yTrn)
      yTrn <- (yTrn - meanYTrn) / sdYTrn
      yTst <- (yTst - meanYTrn) / sdYTrn
      pIn = max(1 - 5e3 / nTrn, 0.75)
      rm(spltObj)
      # VREG
      # if(!silent){
      #   cat("======================================================\n")
      #   cat("VREG\n")
      # }
      # bgnTime <- Sys.time()
      # VeccObj <-
      #   Vecc_path(
      #     var0 = var0,
      #     tau0 = tau0,
      #     sr0 = sr0,
      #     locs = locsTrn,
      #     y = yTrn,
      #     m = m,
      #     k = k,
      #     lambVec = lambVecBrdg,
      #     pen_fun = pen_fun,
      #     dpen_fun = dpen_fun,
      #     ddpen_fun = ddpen_fun,
      #     OOS_score = OOS_rmse,
      #     stop_con_path = stop_con_path,
      #     stop_con_fb = stop_con_OOS1_fb,
      #     miniQCCD = miniQCCD,
      #     miniGrad = miniGrad,
      #     pIn = pIn,
      #     spltSeed = 123,
      #     convQCCD = convQCCD,
      #     convCCD = convCCD,
      #     cAmij = cAmij,
      #     maxIterQCCD = maxIterQCCD,
      #     maxIterCCD = maxIterCCD,
      #     covFn = covFn,
      #     minPosi = minPosi,
      #     mini = mini,
      #     taper = taper,
      #     silent = silent,
      #     nAvg = nAvg
      #   )
      # endTime <- Sys.time()
      # timeUsed <- as.numeric(endTime - bgnTime, units = "secs")
      # scr <- OOS_rmse(VeccObj$theta, locsTrn, locsTst, yTrn, yTst, m, covFn)
      # fpos <- length(setdiff(VeccObj$idx, 1 : d0)) / length(VeccObj$idx)
      # result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "VREG", scr = scr,
      #                       time = timeUsed, fpos = fpos)
      # idx <- idx + 1
      # Fisher
      # if(!silent){
      #   cat("======================================================\n")
      #   cat("Fisher\n")
      # }
      # if((d < 1e3) | (nTrn < 1e4)){
      #   bgnTime <- Sys.time()
      #   FishObj <-
      #     fisher_scoring_meanzero_wrap(locsIdx = 1 : d,
      #                                  m = m,
      #                                  theta = c(var0, rep(sr0, d), tau0),
      #                                  locs = locsTrn,
      #                                  y = yTrn,
      #                                  covFn = covFn,
      #                                  maxIter = maxIterElse,
      #                                  conv = convQCCD,
      #                                  silent = F)
      #   endTime <- Sys.time()
      #   timeUsed <- as.numeric(endTime - bgnTime, units = "secs")
      #   scr <- OOS_rmse(FishObj, locsTrn, locsTst, yTrn, yTst, m, covFn)
      #   idxFish <- which(FishObj[2 : (d + 1)] > 1e-7)
      #   fpos <- length(setdiff(idxFish, 1 : d0)) / length(idxFish)
      #   result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "Fisher",
      #                         scr = scr, time = timeUsed, fpos = fpos)
      #   if(!silent){
      #       cat("======================================================\n")
      #       cat("Results of Fisher scoring:\n")
      #       cat("idx:", idxFish, "\n")
      #       cat("theta:", FishObj[c(1, idxFish + 1, d + 2)], "\n")
      #       cat("score:", scr, "\n")
      #   }
      # }else{
      #   result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "Fisher",
      #                         scr = NA, time = NA, fpos = NA)
      # }
      # idx <- idx + 1
      # PGPR
      # if(!silent){
      #   cat("======================================================\n")
      #   cat("PGPR\n")
      # }
      # if(nTrn < 1e3){
      #   bgnTime <- Sys.time()
      #   PGPRObj <-
      #     PGPR_Yi11(
      #       theta_gen = theta_gen,
      #       ngen = ngenPGPR,
      #       locs = locsTrn,
      #       y = yTrn,
      #       m = m,
      #       lambVec = lambVecBrdg,
      #       pen_fun = pen_brdg,
      #       dpen_fun = dpen_brdg,
      #       ddpen_fun = ddpen_brdg,
      #       OOS_score = OOS_rmse,
      #       stop_con_path = stop_con_path,
      #       pIn = pIn,
      #       spltSeed = 123,
      #       covFn = covFn,
      #       maxIter = maxIterElse,
      #       conv = convQCCD,
      #       silent = silent,
      #       cluster = cluster
      #     )
      #   endTime <- Sys.time()
      #   timeUsed <- as.numeric(endTime - bgnTime, units = "secs")
      #   if(anyNA(PGPRObj$theta)){
      #     result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "PGPR",
      #                           scr = NA, time = NA, fpos = NA)
      #   }else{
      #     scr <- OOS_rmse(PGPRObj$theta, locsTrn, locsTst, yTrn, yTst, m, covFn)
      #     fpos <- length(setdiff(PGPRObj$idx, 1 : d0)) / length(PGPRObj$idx)
      #     result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "PGPR",
      #                           scr = scr, time = timeUsed, fpos = fpos)
      #   }
      # }else{
      #   result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "PGPR", scr = NA,
      #                         time = NA, fpos = NA)
      # }
      # idx <- idx + 1
      # FWD
      # if(!silent){
      #   cat("======================================================\n")
      #   cat("FWD\n")
      # }
      # if((nTrn < 1e4 & d < 1e3) | (nTrn < 1e3)){
      #   bgnTime <- Sys.time()
      #   FWDObj <-
      #     forward_selection_fisher(
      #       var0 = var0,
      #       tau0 = tau0,
      #       sr0 = sr0,
      #       locs = locsTrn,
      #       y = yTrn,
      #       m = m,
      #       OOS_score = OOS_rmse,
      #       stop_con_path = stop_con_path,
      #       pIn = pIn,
      #       spltSeed = 123,
      #       covFn = covFn,
      #       maxIter = maxIterElse,
      #       conv = convQCCD,
      #       silent = silent,
      #       cluster = cluster
      #     )
      #   endTime <- Sys.time()
      #   timeUsed <- as.numeric(endTime - bgnTime, units = "secs")
      #   scr <- OOS_rmse(FWDObj$theta, locsTrn, locsTst, yTrn, yTst, m, covFn)
      #   fpos <- length(setdiff(FWDObj$idx, 1 : d0)) / length(FWDObj$idx)
      #   result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "FWD", scr = scr,
      #                         time = timeUsed, fpos = fpos)
      # }else{
      #   result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "FWD", scr = NA,
      #                         time = NA, fpos = NA)
      # }
      # idx <- idx + 1
      # Lasso
      if(!silent){
        cat("======================================================\n")
        cat("Lasso\n")
      }
      bgnTime <- Sys.time()
      cvLassoObj <- cv.glmnet(x = locsTrn, y = yTrn, alpha = 1, intercept = T)
      endTime <- Sys.time()
      timeUsed <- as.numeric(endTime - bgnTime, units = "secs")
      predLasso <- predict(object = cvLassoObj, s = cvLassoObj$lambda.min, 
                   newx = locsTst)
      scr <- sqrt(mean((predLasso - yTst)^2) / var(yTst))
      idxSel <- which(
        cvLassoObj$glmnet.fit$beta[, cvLassoObj$index["min", "Lambda"]] != 0)
      fpos <- length(setdiff(idxSel, 1 : d0)) / length(idxSel)
      result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "Lasso", 
                            scr = scr, time = timeUsed, fpos = fpos)
      idx <- idx + 1
      # Sparse additive model
      if(!silent){
        cat("======================================================\n")
        cat("Sparse additive model\n")
      }
      bgnTime <- Sys.time()
      idxInsamp <- round(nTrn * pIn)
      samPath <- samQL(X = apply(locsTrn[1 : idxInsamp, ], MARGIN = 2, 
                           FUN = function(x){
                             x + sd(x) / 1e4 * runif(length(x), -1, 1)}), 
                 y = yTrn, nlambda = 15)
      endTime <- Sys.time()
      timeUsed <- as.numeric(endTime - bgnTime, units = "secs")
      predSam <- predict(object = samPath,
                   newdata = locsTrn[(1 + idxInsamp) : nTrn, ])$values
      rmseSam <- 
        apply(predSam, MARGIN = 2, 
              FUN = function(x){
                sqrt(mean((x - yTrn[(1 + idxInsamp) : nTrn])^2) / var(yTst))})
      idxLambda <- which(1 - rmseSam[2:length(rmseSam)] / 
                         rmseSam[1:(length(rmseSam) - 1)] < 0.01)[1]
      if(length(idxLambda) == 0)
        idxLambda <- dim(predSam)[2]
      idxSel <- unique(ceiling(which(samPath$w[, idxLambda] != 0) / samPath$p))
      predSam <- predict(object = samPath, newdata = locsTst)$values
      rmseSam <- 
          apply(predSam, MARGIN = 2, 
                FUN = function(x){sqrt(mean((x - yTst)^2) /var(yTst))})
      scr <- rmseSam[idxLambda]
      fpos <- length(setdiff(idxSel, 1 : d0)) / length(idxSel)
      result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "SAM", 
                            scr = scr, time = timeUsed, fpos = fpos)
      idx <- idx + 1
      # Regression tree
      if(!silent){
        cat("======================================================\n")
        cat("Regression tree\n")
      }
      bgnTime <- Sys.time()
      regTreeObj <- reg_tree_wrap(locsTrn, yTrn, locsTst, yTst, pIn)
      endTime <- Sys.time()
      timeUsed <- as.numeric(endTime - bgnTime, units = "secs")
      scr <- regTreeObj$rmseScr
      fpos <- length(setdiff(regTreeObj$idxSel, 1 : d0)) / 
        length(regTreeObj$idxSel)
      result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "Tree", 
                            scr = scr, time = timeUsed, fpos = fpos)
      idx <- idx + 1
      # KISS-GP
      if(!silent){
        cat("======================================================\n")
        cat("KISS-GP\n")
      }
      if(d < 1e3){
        bgnTime <- Sys.time()
        kissGPObj <- KISS_GP_wrap(locsTrn, yTrn, locsTst, yTst)
        endTime <- Sys.time()
        timeUsed <- as.numeric(endTime - bgnTime, units = "secs")
        scr <- kissGPObj$rmseScr
        fpos <- NA
        result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "KISS", scr = scr,
                              time = timeUsed, fpos = fpos)
      }else{
        result[idx, ] <- list(n = nTrn, d = d, rho = rho, mtd = "KISS", scr = NA,
                              time = NA, fpos = NA)
      }
      idx <- idx + 1
    }
```

```{r save results, eval = T}
save(result, file = paste0("sim_GP_result_seed", seed, ".RData"))
```

```{r plot results, eval = F}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(scales)
library(reshape)
library(patchwork)
dataFn <- dir(".", pattern = "sim_GP.*\\.RData")
rm(rsltAll)
for(fn in dataFn){
    load(fn)
    if(!exists("rsltAll")){
        rsltAll <- as_tibble(result)
    }else{
        rsltAll <- rsltAll %>% bind_rows(as_tibble(result))
    }
}
rsltAll$time <- rsltAll$time / 60
rsltAll$mtd[rsltAll$mtd == "VREG"] <- "VGPR"
my_plot <- function(mydf){
    d <- unique(mydf$d)
    rho <- unique(mydf$rho)
    measure <- unique(mydf$measure)
    dMin <- min(rsltAll$d)
    plt <- ggplot(data = mydf, 
                  aes(x = n, y = value, col = mtd, shape = mtd, group = mtd)) +
        geom_point(size = 5) + 
        scale_shape(solid = FALSE) +
        scale_shape_manual(values=seq(0, length(unique(mydf$mtd)) - 1)) +
        geom_line() +
        theme(text = element_text(size = 20), legend.title = element_blank(),
              legend.key.height = unit(3, 'cm'), 
              plot.title = element_text(hjust = 0.5))
    if(measure == "scr")
        plt <- plt + ggtitle(paste0(d,  " ",
                                    switch((rho > 0) + 1, "ind", "dep"), 
                                    " var")) +
        scale_y_continuous(trans = log2_trans())
    if(rho > 0 | d != dMin){
        plt <- plt + theme(axis.title.y = element_blank())
    }else
        plt <- plt + ylab(
          c("RMSE", "FPos", "Time")[which(c("scr", "fpos", "time") == measure)])
    if(measure != "time"){
        plt <- plt + 
            theme(axis.title.x = element_blank(), 
                  axis.ticks.x=element_blank(), axis.text.x=element_blank())
    }
    plt
}
plt <- rsltAll %>% mutate(n = factor(n)) %>% 
  group_by(n, d, rho, mtd) %>% 
  summarise(scr = mean(scr), fpos = mean(fpos, na.rm = T), 
            time = mean(time)) %>% 
  pivot_longer(cols = c("scr", "time", "fpos"), names_to = "measure") %>% 
  mutate(measure = factor(measure, levels = c("scr", "fpos", "time"))) %>%
  group_by(measure, d, rho) %>% group_split() %>% map(my_plot) %>% 
  reduce(get("+"))
plt + plot_layout(ncol = 4, guides = "collect")
ggsave("sim_result.pdf", height = 10, width = 14)
```







































