---
title: "Generate Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

* Generate $10^5$ observations from a 3D grid, using `RandomFields`
* Generate fake predictors
* Save the data

## Simulation

The simulation study.

```{r install the moderated GpGp Pkg}
library(lhs)
library(RandomFields)
set.seed(123)
```

Generate observations.
```{r gen obs}
RFoptions(spConform=FALSE)
set.seed(123)
var <- 1
tausq <- 0.05^2
r0 <- c(2, 1, 0.5)
loc1 <- seq(from = 0, to = 1, length.out = 100)
loc1 <- loc1 * sqrt(100) / sqrt(sum(loc1^2))
loc2 <- seq(from = 0, to = 1, length.out = 100)
loc2 <- loc2 * sqrt(100) / sqrt(sum(loc2^2))
loc3 <- seq(from = 0, to = 1, length.out = 10)
loc3 <- loc3 * sqrt(10) / sqrt(sum(loc3^2))
scale <- 1 / max(loc1, loc2, loc3)
model <- RMwhittle(var = var, scale = scale, nu = 2.5)
y <- RFsimulate(model, 
                x = loc1 * r0[1] * scale, 
                y = loc2 * r0[2] * scale,
                z = loc3 * r0[3] * scale,
                grid = T)
```

Define `d`.
```{r d and m}
d <- 1e3
```

Build the independent predictors and `y`.
```{r indep predictors}
n <- length(y)
locsT <- matrix(NA, n, 3)
yTmp <- rep(NA, n)
for(i1 in 1 : 100)
  for(i2 in 1 : 100)
  {
    idx <- ((i1 - 1) * 1000 + (i2 - 1) * 10 + 1) : 
      ((i1 - 1) * 1000 + (i2 - 1) * 10 + 10) 
    locsT[idx, ] <- cbind(rep(loc1[i1], length(loc3)), 
                          rep(loc2[i2], length(loc3)), 
                          loc3)
    yTmp[idx] <- y[i1, i2, ]
  }
y <- yTmp
locsF <- randomLHS(n, d - 3)
locsF <- locsF * outer(rep(sqrt(n), n), 
                     1 / sqrt(colSums(locsF^2)))
locs <- cbind(locsT, locsF)
cat("Independent predictors generated \n")
```

Add noise to `y`.
```{r demean y}
y <- y + rnorm(n, 0, var * tausq)
```

Set aside OOS dataset.
```{r OOS}
nOOS <- 5e3
idxOOS <- sample(1 : n, nOOS)
yOOS <- y[idxOOS]
locsOOS <- locs[idxOOS, , drop = F]
y <- y[-idxOOS]
locs <- locs[-idxOOS, , drop = F]
n <- n - nOOS
cat("Out of sample data separated\n")
```

Store results.
```{r save the result}
save(list = c("d", "n", "locs", "y", "nOOS", "locsOOS", "yOOS", "var", "r0",
              "tausq"), 
     file = paste0("simulation_data", ".RData"))
```
















