---
title: "dataset_prep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Goal

To prepare different datasets into the desired format.

## Slice Localization

```{r read and rearrange cols, eval = T}
dataFn <- "slice_localization_data.csv"
if(file.exists(dataFn)){
  dataSet <- read.csv(dataFn, header = F)
}else{
  dataSet <- read.csv(paste0("../../data/", dataFn), header = F)
}
colIDObj <- 386
d <- ncol(dataSet) - 1
tmp <- dataSet[, d + 1]
dataSet[, d + 1] <- dataSet[, colIDObj]
dataSet[, colIDObj] <- tmp
```

```{r create fake covariates, eval = T}
set.seed(123)
dFake <- 1e3 - d
if(dFake > 0){
  predFakeIndep <- matrix(rnorm(dFake * nrow(dataSet)), nrow(dataSet), dFake, 
                     dimnames = list(row = NULL, 
                                     col = paste0("FV", (d + 1) : (d + dFake))))
  dataSetIndep <- cbind(dataSet[, 1 : d], predFakeIndep, dataSet[, d + 1])
  weightMat <- matrix(runif(d * dFake), d, dFake)
  predFakeDep <- as.matrix(dataSet[, 1 : d]) %*% weightMat
  dataSetDep <- cbind(dataSet[, 1 : d], predFakeDep, dataSet[, d + 1])
  d <- d + dFake
}
```

```{r standardize the covariates, eval = T}
sdVec <- apply(dataSet[, 1 : (d - dFake)], MARGIN = 2, sd)
constColIdx <- which(sdVec == 0)
dataSetIndep <- dataSetIndep[, - constColIdx]
dataSetDep <- dataSetDep[, - constColIdx]
d <- d - length(constColIdx)
# First col is ppl idx
dataSetIndep[, 2 : d] <- apply(dataSetIndep[, 2 : d], MARGIN = 2, 
                          function(x){(x - mean(x)) / sd(x)})
dataSetDep[, 2 : d] <- apply(dataSetDep[, 2 : d], MARGIN = 2, 
                          function(x){(x - mean(x)) / sd(x)})
```

```{r split dataset, eval = T}
set.seed(123)
pplIdx <- sample(unique(dataSet[, 1]), 
                 size = round(length(unique(dataSet[, 1])) * 0.75))
idxTrain <- which(dataSet[, 1] %in% pplIdx)
idxTest <- setdiff(1 : nrow(dataSet), idxTrain)
dataSetIndepTrain <- dataSetIndep[idxTrain, , drop = F]
dataSetIndepTest <- dataSetIndep[idxTest, , drop = F]
dataSetDepTrain <- dataSetDep[idxTrain, , drop = F]
dataSetDepTest <- dataSetDep[idxTest, , drop = F]
```

```{r remove useless col, eval = T}
dummyIdx <- c(1)
if(length(dummyIdx) > 0){
  dataSetIndepTrain <- dataSetIndepTrain[, - dummyIdx]
  dataSetIndepTest <- dataSetIndepTest[, - dummyIdx]
  dataSetDepTrain <- dataSetDepTrain[, - dummyIdx]
  dataSetDepTest <- dataSetDepTest[, - dummyIdx]
}
d <- d - length(dummyIdx)
```

Write into files, train/test with/without fake predictors
```{r write into files, eval = T}
write.table(x = dataSetIndepTrain, row.names = F, sep = ",",
          col.names = F, file = gsub("\\.", "_wf_train.", dataFn))
write.table(x = dataSetIndepTrain[, - ((d - dFake + 1) : d), drop = F], 
            row.names = F, sep = ",",
            col.names = F, file = gsub("\\.", "_train.", dataFn))
write.table(x = dataSetIndepTest, row.names = F, sep = ",",
          col.names = F, file = gsub("\\.", "_wf_test.", dataFn))
write.table(x = dataSetIndepTest[, - ((d - dFake + 1) : d), drop = F], 
            row.names = F, sep = ",",
            col.names = F, file = gsub("\\.", "_test.", dataFn))
write.table(x = dataSetDepTrain, row.names = F, sep = ",",
          col.names = F, file = gsub("\\.", "_wf_dep_train.", dataFn))
write.table(x = dataSetDepTest, row.names = F, sep = ",",
          col.names = F, file = gsub("\\.", "_wf_dep_test.", dataFn))
```

After pre-processing which screens out constant covairates and people's indices, we are left with $379$ non-fake covariates.