---
title: "RMwhittle_exp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r clean env, echo = FALSE}
rm(list = ls())
```

```{r load libs, echo = FALSE}
library(RandomFields)
library(lhs)
```

## Goal

To experiment with `RMwhittle` and see
* if the produced kernel is Matern
* how long it will take to simulate `1e5` responses

## Experiment

```{r generate locs}
n <- 1e5
d <- 1e3
locs <- lhs::randomLHS(n, d)
locs <- locs * outer(rep(sqrt(n), n), 1 / sqrt(colSums(locs^2)))
```

```{r parms for GP kernel}
r <- c(10, 5, 2, 1, 0.5, rep(0, d - 5))
sigmasq <- 1.0 # variance
tausq <- 0.05^2 # nugget
nu <- 2.5
```

```{r simulate GP Chol mtd}
if(n <= 1e4)
{
  startTime <- Sys.time()
  set.seed(123)
  covM <- GpGp::matern25_scaledim_relevance(c(sigmasq, r, tausq), locs)
  cholM <- t(chol(covM))
  yChol <- as.vector(cholM %*% rnorm(n))
  rm(covM, cholM)
  endTime <- Sys.time()
  cat("simulate GP Chol mtd", 
      as.numeric(difftime(endTime, startTime, units = "secs")))
}
```

```{r simulate GP RMwhittle}
startTime <- Sys.time()
RFoptions(seed = 123, spConform = FALSE)
model <- RMwhittle(nu = nu, scale = 1, var = sigmasq,  
                   Aniso = diag(r[1 : 5])) + 
  RMnugget(var= sigmasq * tausq)
yRM <- RFsimulate(model, locs[, 1 : 5])
endTime <- Sys.time()
cat("simulate GP RMwhittle", 
    as.numeric(difftime(endTime, startTime, units = "secs")))
```
Notice that when setting the seeds to be the same, RFsimulate and the Cholesky method produce the same replicate. Hence, we can use the L1 norm to examine the correctness, which seems positive.
```{r compare yRM and yChol}
if(n <= 1e4)
{
  cat(sum(abs(yChol - yRM)))
}
```




